<?php

namespace App\Domains\AI\Actions;

use App\Domains\AI\Providers\AIProviderChain;
use Illuminate\Support\Facades\Log;

class GenerateProjectSchemaAction
{
  public function __construct(
    private AIProviderChain $chain
  ) {}

  public function execute(string $userPrompt, array $conversationHistory = []): array
  {
    $systemPrompt = $this->buildSystemPrompt();
    $fullPrompt   = $this->buildPromptWithHistory($userPrompt, $conversationHistory);

    try {
      // ✅ الـ chain يجرب كل provider تلقائياً
      $result  = $this->chain->generate($systemPrompt, $fullPrompt);
      $rawText = $result['text'];

      Log::info("[AI Schema] Generated by: {$result['provider']}");

      // لو في providers فشلت قبل النجاح — سجّل تحذير
      if (!empty($result['errors'])) {
        Log::warning("[AI Schema] Fallback used. Failed providers: " .
          collect($result['errors'])->keys()->implode(', '));
      }

      $parsedData = $this->parseJson($rawText);

      return [
        'success'          => true,
        'ai_chat_bubble'   => $parsedData['assistant_message'] ?? 'لم يتم استلام رسالة.',
        'technical_schema' => $parsedData['schema']            ?? [],
        'provider_used'    => $result['provider'],
      ];
    } catch (\Exception $e) {
      Log::error("[AI Schema] All providers failed: " . $e->getMessage());
      throw $e;
    }
  }

  // ─────────────────────────────────────────────────────────
  private function buildSystemPrompt(): string
  {
    return <<<EOT
Role: You are HyperCore AI, a Senior System Architect for HyperCore CMS — 
a modular Laravel-based platform. Transform user business ideas into a 
production-ready technical schema IMMEDIATELY.

════════════════════════════════════════
1. THE "NO-QUESTIONS" MANDATE (CRITICAL)
════════════════════════════════════════
- NEVER ask for clarifications, project names, or languages.
- ACT IMMEDIATELY using logical assumptions.
- DEFAULT LANGUAGES: ["ar", "en"] unless specified.
- DEFAULT PROJECT NAME: Generate a creative professional name.
- LANGUAGE MATCHING RULE: Detect the user's language and respond in the SAME language for all conversational parts.

════════════════════════════════════════
2. INTELLIGENT MODULE ACTIVATION
════════════════════════════════════════
Activate modules based on business model:

| Module    | Trigger Keywords                                               |
|-----------|---------------------------------------------------------------|
| cms       | ALWAYS active (blog, news, pages, content)                   |
| ecommerce | sell, buy, store, products, cart, payment, checkout, orders  |
| booking   | appointment, rent, schedule, reserve, slot, availability      |

COMBINATION RULE:
- "Real Estate with listings" → [cms, ecommerce]
- "Clinic with appointments" → [cms, booking]
- "Mall with stores and reservations" → [cms, ecommerce, booking]

════════════════════════════════════════
3. BUILT-IN vs CUSTOM PROTOCOL
════════════════════════════════════════
NATIVE (DO NOT recreate as custom types):
- ecommerce: Cart, Orders, OrderItems, Payments, Offers, Wishlist, Returns
- booking: Resources, Bookings, ResourceAvailabilities, CancellationPolicies
- cms: Projects, DataTypes, DataEntries, Collections, SEO, Ratings

CUSTOM DATA TYPES: Only for unique business entities.

════════════════════════════════════════
4. CONVERSATION CONTINUITY (CRITICAL)
════════════════════════════════════════
- If conversation history is provided, you are in an EDIT/UPDATE mode.
- Read the previous schema carefully and apply the user's requested changes.
- ALWAYS return the COMPLETE updated schema (not just the changes).
- Maintain previously defined data types and fields unless the user asks to remove them.

════════════════════════════════════════
5. FIELD TYPES — EXACT ALLOWED VALUES
════════════════════════════════════════
Use ONLY: "text", "number", "boolean", "select", "file", "json", "relation".

FIELD STRUCTURE:
{
  "name": "snake_case_name",
  "type": "exact_type",
  "required": true/false,
  "translatable": true/false,
  "validation_rules": [],
  "settings": {}
}

════════════════════════════════════════
6. RELATIONS PROTOCOL
════════════════════════════════════════
Use EXACT types: "belongs_to", "has_many", "many_to_many".
Use "related_data_type_name" in settings.

════════════════════════════════════════
7. OUTPUT PROTOCOL — STRICT JSON ONLY
════════════════════════════════════════
- Return ONLY a single JSON object. No text before or after.
- DYNAMIC LANGUAGE RULE: The "assistant_message", "description", and all "labels" or "notes" MUST be written in the SAME language the user used in their prompt (e.g., if the user asks in English, respond in English. If in Arabic, respond in Arabic).

{
  "assistant_message": "Professional response in the USER'S LANGUAGE.",
  "schema": {
    "project_info": {
      "name": "Project Name",
      "slug": "url-friendly-slug",
      "languages": ["ar", "en"],
      "modules": ["cms"],
      "description": "Brief technical description in the USER'S LANGUAGE."
    },
    "custom_data_types": [
      {
        "name": "EntityName",
        "slug": "entity-slug",
        "description": "Description in USER'S LANGUAGE.",
        "fields": [...]
      }
    ],
    "relations": [...],
    "native_modules_notes": {
      "ecommerce": "Explanation in USER'S LANGUAGE",
      "booking": "Explanation in USER'S LANGUAGE"
    }
  }
}

FINAL COMMAND: Detect user language, analyze prompt, and return the JSON immediately.
EOT;
  }

  // ─────────────────────────────────────────────────────────
  private function buildPromptWithHistory(
    string $currentPrompt,
    array  $history
  ): string {
    if (empty($history)) {
      return $currentPrompt;
    }

    $context  = "=== CONVERSATION HISTORY ===\n\n";

    foreach ($history as $message) {
      $role     = $message['role'] === 'user' ? 'USER' : 'ASSISTANT';
      $context .= "[{$role}]:\n{$message['content']}\n\n";

      if ($message['role'] === 'assistant' && !empty($message['schema'])) {
        $context .= "[PREVIOUS SCHEMA]:\n";
        $context .= json_encode($message['schema'], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
        $context .= "\n\n";
      }
    }

    $context .= "=== CURRENT REQUEST ===\n{$currentPrompt}\n\n";
    $context .= "IMPORTANT: Return the COMPLETE updated schema with all changes applied.";

    return $context;
  }

  // ─────────────────────────────────────────────────────────
  private function parseJson(string $text): array
  {
    $text  = str_replace(['```json', '```'], '', $text);
    $text  = trim($text);
    $start = strpos($text, '{');
    $end   = strrpos($text, '}');

    if ($start !== false && $end !== false) {
      $text = substr($text, $start, $end - $start + 1);
    }

    $decoded = json_decode($text, true, 512, JSON_UNESCAPED_UNICODE);
    return is_array($decoded) ? $decoded : [];
  }
}
