<?php

namespace App\Domains\AI\Actions;

use App\Domains\AI\Providers\AIProviderChain;
use Illuminate\Support\Facades\Log;

class GenerateProjectSchemaAction
{
  public function __construct(
    private AIProviderChain $chain
  ) {}

  public function execute(string $userPrompt, array $conversationHistory = []): array
  {
    $systemPrompt = $this->buildSystemPrompt();
    $fullPrompt   = $this->buildPromptWithHistory($userPrompt, $conversationHistory);

    try {
      // ✅ الـ chain يجرب كل provider تلقائياً
      $result  = $this->chain->generate($systemPrompt, $fullPrompt);
      $rawText = $result['text'];

      Log::info("[AI Schema] Generated by: {$result['provider']}");

      // لو في providers فشلت قبل النجاح — سجّل تحذير
      if (!empty($result['errors'])) {
        Log::warning("[AI Schema] Fallback used. Failed providers: " .
          collect($result['errors'])->keys()->implode(', '));
      }

      $parsedData = $this->parseJson($rawText);

      return [
        'success'          => true,
        'ai_chat_bubble'   => $parsedData['assistant_message'] ?? 'لم يتم استلام رسالة.',
        'technical_schema' => $parsedData['schema']            ?? [],
        'provider_used'    => $result['provider'],
      ];
    } catch (\Exception $e) {
      Log::error("[AI Schema] All providers failed: " . $e->getMessage());
      throw $e;
    }
  }

  // ─────────────────────────────────────────────────────────
  private function buildSystemPrompt(): string
  {
    return <<<EOT
Role: You are HyperCore AI, a Senior System Architect for HyperCore CMS — 
a modular Laravel-based platform. Transform user business ideas into a 
production-ready technical schema IMMEDIATELY.

════════════════════════════════════════
1. THE "NO-QUESTIONS" MANDATE (CRITICAL)
════════════════════════════════════════
- NEVER ask for clarifications, project names, or languages.
- ACT IMMEDIATELY using logical assumptions.
- DEFAULT LANGUAGES: ["ar", "en"] unless specified.
- DEFAULT PROJECT NAME: Generate a creative professional name.

════════════════════════════════════════
2. INTELLIGENT MODULE ACTIVATION
════════════════════════════════════════
Activate modules based on business model:
- cms:       ALWAYS active
- ecommerce: sell, buy, store, products, cart, payment, orders
- booking:   appointment, rent, schedule, reserve, slot, availability

════════════════════════════════════════
3. BUILT-IN vs CUSTOM PROTOCOL
════════════════════════════════════════
NATIVE (DO NOT recreate):
- ecommerce: Cart, Orders, Payments, Offers, Wishlist, Returns
- booking:   Resources, Bookings, Availabilities, Policies
- cms:       Projects, DataTypes, DataEntries, Collections, SEO, Ratings

CUSTOM: Only unique business entities.

════════════════════════════════════════
4. CONVERSATION CONTINUITY
════════════════════════════════════════
- If history provided → EDIT mode. Apply changes to existing schema.
- ALWAYS return the COMPLETE updated schema.

════════════════════════════════════════
5. FIELD TYPES
════════════════════════════════════════
Exact types: text, number, boolean, select, file, json, relation

FIELD STRUCTURE:
{
  "name": "snake_case_name",
  "type": "exact_type",
  "required": true/false,
  "translatable": true/false,
  "validation_rules": ["rule1"],
  "settings": {}
}

SETTINGS:
- text:    { "placeholder": "...", "default": null }
- number:  { "default": 0, "step": 1 }
- boolean: { "default": false }
- select:  { "options": ["a","b"], "default": "a", "multiple": false }
- file:    { "multiple": false, "allowed_types": ["jpg","png"], "max_size": 5120 }
- json:    { "schema": null }
- relation:{ "relation_type": "belongs_to|has_many|many_to_many",
             "related_data_type_name": "EntityName", "multiple": false }

TRANSLATABLE: true for text/description/title, false for numbers/booleans/files.

════════════════════════════════════════
6. OUTPUT — STRICT JSON ONLY
════════════════════════════════════════
{
  "assistant_message": "رسالة بالعربية",
  "schema": {
    "project_info": {
      "name": "", "slug": "", "languages": ["ar","en"],
      "modules": ["cms"], "description": ""
    },
    "custom_data_types": [
      {
        "name": "", "slug": "", "description": "",
        "fields": [...]
      }
    ],
    "relations": [
      {
        "source": "", "target": "", "type": "belongs_to",
        "field_name": "", "label": "", "required": false
      }
    ],
    "native_modules_notes": {}
  }
}

FINAL COMMAND: Return JSON immediately. No text outside JSON.
EOT;
  }

  // ─────────────────────────────────────────────────────────
  private function buildPromptWithHistory(
    string $currentPrompt,
    array  $history
  ): string {
    if (empty($history)) {
      return $currentPrompt;
    }

    $context  = "=== CONVERSATION HISTORY ===\n\n";

    foreach ($history as $message) {
      $role     = $message['role'] === 'user' ? 'USER' : 'ASSISTANT';
      $context .= "[{$role}]:\n{$message['content']}\n\n";

      if ($message['role'] === 'assistant' && !empty($message['schema'])) {
        $context .= "[PREVIOUS SCHEMA]:\n";
        $context .= json_encode($message['schema'], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
        $context .= "\n\n";
      }
    }

    $context .= "=== CURRENT REQUEST ===\n{$currentPrompt}\n\n";
    $context .= "IMPORTANT: Return the COMPLETE updated schema with all changes applied.";

    return $context;
  }

  // ─────────────────────────────────────────────────────────
  private function parseJson(string $text): array
  {
    $text  = str_replace(['```json', '```'], '', $text);
    $text  = trim($text);
    $start = strpos($text, '{');
    $end   = strrpos($text, '}');

    if ($start !== false && $end !== false) {
      $text = substr($text, $start, $end - $start + 1);
    }

    $decoded = json_decode($text, true, 512, JSON_UNESCAPED_UNICODE);
    return is_array($decoded) ? $decoded : [];
  }
}
